/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/sign-up": {
    /** Creates a new user account using an email and password. Upon successful registration, returns the user object in the response body, while access and refresh tokens are included in the response headers, effectively signing in the user. */
    post: operations["eventio-auth-signUp"];
  };
  "/auth/sign-in": {
    /** Authenticates a user with an email and password. Returns the user object in the response body, while access and refresh tokens are included in the response headers. */
    post: operations["eventio-auth-signIn"];
  };
  "/auth/refresh": {
    /** Generates a new access token using a valid refresh token. Returns the user object in the response body, while new access token is included in the response headers. */
    post: operations["eventio-auth-refreshToken"];
  };
  "/events": {
    get: operations["eventio-events-getAll"];
    post: operations["eventio-events-create"];
  };
  "/events/{id}": {
    get: operations["eventio-events-getById"];
    delete: operations["eventio-events-delete"];
    patch: operations["eventio-events-update"];
  };
  "/events/{id}/attendees/me": {
    post: operations["eventio-events-attend"];
    delete: operations["eventio-events-unattend"];
  };
}

export interface components {
  responses: {
    /** Error response */
    error: {
      content: {
        "application/json": {
          message: string;
          code: string;
          issues?: {
            message: string;
          }[];
        };
      };
    };
  };
}

export interface operations {
  /** Creates a new user account using an email and password. Upon successful registration, returns the user object in the response body, while access and refresh tokens are included in the response headers, effectively signing in the user. */
  "eventio-auth-signUp": {
    parameters: {};
    responses: {
      /** Successful response */
      200: {
        headers: {};
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
        };
      };
      default: components["responses"]["error"];
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
          firstName: string;
          lastName: string;
          password: string;
        };
      };
    };
  };
  /** Authenticates a user with an email and password. Returns the user object in the response body, while access and refresh tokens are included in the response headers. */
  "eventio-auth-signIn": {
    parameters: {};
    responses: {
      /** Successful response */
      200: {
        headers: {};
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
        };
      };
      default: components["responses"]["error"];
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
          password: string;
        };
      };
    };
  };
  /** Generates a new access token using a valid refresh token. Returns the user object in the response body, while new access token is included in the response headers. */
  "eventio-auth-refreshToken": {
    parameters: {};
    responses: {
      /** Successful response */
      200: {
        headers: {};
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
        };
      };
      default: components["responses"]["error"];
    };
    requestBody: {
      content: {
        "application/json": {
          refreshToken: string;
        };
      };
    };
  };
  "eventio-events-getAll": {
    parameters: {};
    responses: {
      /** Successful response */
      200: {
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            /** Format: date-time */
            startsAt: string;
            capacity: number;
            /** Format: uuid */
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            attendees: {
              /** Format: uuid */
              id: string;
              firstName: string;
              lastName: string;
              email: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            owner: {
              /** Format: uuid */
              id: string;
              firstName: string;
              lastName: string;
              email: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          }[];
        };
      };
      default: components["responses"]["error"];
    };
  };
  "eventio-events-create": {
    parameters: {};
    responses: {
      /** Successful response */
      200: {
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            /** Format: date-time */
            startsAt: string;
            capacity: number;
            /** Format: uuid */
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            attendees: {
              /** Format: uuid */
              id: string;
              firstName: string;
              lastName: string;
              email: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            owner: {
              /** Format: uuid */
              id: string;
              firstName: string;
              lastName: string;
              email: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
      default: components["responses"]["error"];
    };
    requestBody: {
      content: {
        "application/json": {
          title: string;
          description: string;
          /** Format: date-time */
          startsAt: string;
          capacity: number;
        };
      };
    };
  };
  "eventio-events-getById": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Successful response */
      200: {
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            /** Format: date-time */
            startsAt: string;
            capacity: number;
            /** Format: uuid */
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            attendees: {
              /** Format: uuid */
              id: string;
              firstName: string;
              lastName: string;
              email: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            owner: {
              /** Format: uuid */
              id: string;
              firstName: string;
              lastName: string;
              email: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
      default: components["responses"]["error"];
    };
  };
  "eventio-events-delete": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Successful response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      default: components["responses"]["error"];
    };
  };
  "eventio-events-update": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Successful response */
      200: {
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            /** Format: date-time */
            startsAt: string;
            capacity: number;
            /** Format: uuid */
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            attendees: {
              /** Format: uuid */
              id: string;
              firstName: string;
              lastName: string;
              email: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            owner: {
              /** Format: uuid */
              id: string;
              firstName: string;
              lastName: string;
              email: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
      default: components["responses"]["error"];
    };
    requestBody: {
      content: {
        "application/json": {
          title?: string;
          description?: string;
          /** Format: date-time */
          startsAt?: string;
          capacity?: number;
        };
      };
    };
  };
  "eventio-events-attend": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Successful response */
      200: {
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            /** Format: date-time */
            startsAt: string;
            capacity: number;
            /** Format: uuid */
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            attendees: {
              /** Format: uuid */
              id: string;
              firstName: string;
              lastName: string;
              email: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            owner: {
              /** Format: uuid */
              id: string;
              firstName: string;
              lastName: string;
              email: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
      default: components["responses"]["error"];
    };
  };
  "eventio-events-unattend": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Successful response */
      200: {
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            /** Format: date-time */
            startsAt: string;
            capacity: number;
            /** Format: uuid */
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            attendees: {
              /** Format: uuid */
              id: string;
              firstName: string;
              lastName: string;
              email: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            owner: {
              /** Format: uuid */
              id: string;
              firstName: string;
              lastName: string;
              email: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
      default: components["responses"]["error"];
    };
  };
}

export interface external {}
